import Head from 'next/head'
import React from 'react'
import Header from './Header'
import Menu from './Menu'
import {useEffect} from 'react';
const Layout = ({children,pagina}) => {

  
   
    // const element2 = ref.current;
    // console.log(element2);

 
    useEffect(() => {
      const body = document.querySelector(".body");
      const sidebar = body.querySelector(".sidebar");
      const toggle = body.querySelector(".toggle");
      const searchBtn = body.querySelector(".search-box");
      const modeSwtich = body.querySelector(".toggle-switch");
      const modeText = body.querySelector(".mode-text");
  
      const handleToggleClick = () => {
        sidebar.classList.toggle("close");
      };
  
      // const handleSearchClick = () => {
      //   sidebar.classList.remove("close");
      // };
  
      // const handleModeSwitchClick = () => {
      //   body.classList.toggle("dark");
  
      //   if (body.classList.contains("dark")) {
      //     modeText.innerText = "Light Mode";
      //   } else {
      //     modeText.innerText = "Dark Mode";
      //   }
      // };
      handleToggleClick();
      toggle.addEventListener("click", handleToggleClick);
     // searchBtn.addEventListener("click", handleSearchClick);
      // modeSwtich.addEventListener("click", handleModeSwitchClick);
  
      return () => {
        toggle.removeEventListener("click", handleToggleClick);
        //searchBtn.removeEventListener("click", handleSearchClick);
        // modeSwtich.removeEventListener("click", handleModeSwitchClick);
      };
    }, []);







  return (
        <div>
            <Head>
                <title>PROD EMPLEOS ADMIN-{pagina}</title>
                <meta name="description" content="Generated by create next app"/>
                {/* <link href='https://unpkg.com/boxicons@2.1.2/css/boxicons.min.css' rel='stylesheet'> */}
                {/* <link rel="stylesheet" href="style01.css"/> */}
            </Head>
        <div className='body'>
              
                <nav className="sidebar close">
               
                    <Header /> 
                    <Menu/>
              
                </nav>
                <section className="home">
                <div className="text"> {children}</div>
                </section>
              

                {/* <Footer /> */}
        </div>

            <style jsx>{`
                styles/globals.css
              `}</style>


        </div>
  )
}

export default Layout