export const dataIndustria= [
    {"label": "Tecnología de la Información (TI) y Servicios", "value": "Tecnología de la Información (TI) y Servicios"},
    {"label": "Salud y Cuidado de la Salud", "value": "Salud y Cuidado de la Salud"},
    {"label": "Finanzas y Banca", "value": "Finanzas y Banca"},
    {"label": "Manufactura", "value": "Manufactura"},
    {"label": "Retail y Comercio", "value": "Retail y Comercio"},
    {"label": "Educación", "value": "Educación"},
    {"label": "Telecomunicaciones", "value": "Telecomunicaciones"},
    {"label": "Energía y Servicios Públicos", "value": "Energía y Servicios Públicos"},
    {"label": "Medios de Comunicación y Entretenimiento", "value": "Medios de Comunicación y Entretenimiento"},
    {"label": "Transporte y Logística", "value": "Transporte y Logística"},
    {"label": "Alimentación y Bebidas", "value": "Alimentación y Bebidas"},
    {"label": "Automotriz", "value": "Automotriz"},
    {"label": "Aeroespacial y Defensa", "value": "Aeroespacial y Defensa"},
    {"label": "Construcción y Desarrollo", "value": "Construcción y Desarrollo"},
    {"label": "Turismo y Hospitalidad", "value": "Turismo y Hospitalidad"},
    {"label": "Servicios Profesionales y Consultoría", "value": "Servicios Profesionales y Consultoría"},
    {"label": "Bienes Raíces", "value": "Bienes Raíces"},
    {"label": "Farmacéutica y Ciencias de la Vida", "value": "Farmacéutica y Ciencias de la Vida"},
    {"label": "Recursos Naturales y Agricultura", "value": "Recursos Naturales y Agricultura"},
    {"label": "Gobierno y Organizaciones sin Fines de Lucro", "value": "Gobierno y Organizaciones sin Fines de Lucro"},
    {"label": "Investigación y Desarrollo", "value": "Investigación y Desarrollo"},
    {"label": "Moda y Diseño", "value": "Moda y Diseño"},
    {"label": "Deporte y Recreación", "value": "Deporte y Recreación"},
    {"label": "Publicidad y Marketing", "value": "Publicidad y Marketing"},
    {"label": "Servicios Ambientales y Sostenibilidad", "value": "Servicios Ambientales y Sostenibilidad"},
    {"label": "Servicios Legales", "value": "Servicios Legales"},
    {"label": "Industria Química", "value": "Industria Química"},
    {"label": "Industria de la Construcción Naval", "value": "Industria de la Construcción Naval"},
    {"label": "Industria Metalúrgica", "value": "Industria Metalúrgica"},
    {"label": "Industria del Plástico", "value": "Industria del Plástico"},
    {"label": "Industria del Vidrio", "value": "Industria del Vidrio"},
    {"label": "Industria de la Madera y el Papel", "value": "Industria de la Madera y el Papel"},
    {"label": "Industria Textil y del Vestido", "value": "Industria Textil y del Vestido"},
    {"label": "Industria Electrónica", "value": "Industria Electrónica"},
    {"label": "Industria Farmacéutica", "value": "Industria Farmacéutica"},
    {"label": "Industria del Acero", "value": "Industria del Acero"},
    {"label": "Industria del Caucho", "value": "Industria del Caucho"},
    {"label": "Industria de la Cerámica", "value": "Industria de la Cerámica"},
    {"label": "Industria del Cuero y Calzado", "value": "Industria del Cuero y Calzado"},
    {"label": "Industria del Juguete", "value": "Industria del Juguete"},
    {"label": "Industria de Instrumentos Ópticos y de Precisión", "value": "Industria de Instrumentos Ópticos y de Precisión"},
    {"label": "Industria de la Imagen y Sonido", "value": "Industria de la Imagen y Sonido"},
    {"label": "Industria de la Joyería", "value": "Industria de la Joyería"},
    {"label": "Industria de Maquinaria y Equipo", "value": "Industria de Maquinaria y Equipo"},
    {"label": "Industria de Servicios Financieros", "value": "Industria de Servicios Financieros"},
    {"label": "Industria de Servicios de Tecnología de la Información", "value": "Industria de Servicios de Tecnología de la Información"},
    {"label": "Industria del Entretenimiento", "value": "Industria del Entretenimiento"},
  {"label": "Industria del Petróleo y Gas", "value": "Industria del Petróleo y Gas"},
  {"label": "Industria del Plástico y Caucho", "value": "Industria del Plástico y Caucho"},
  {"label": "Industria del Retail", "value": "Industria del Retail"},
  {"label": "Industria del Software y Desarrollo Web", "value": "Industria del Software y Desarrollo Web"},
  {"label": "Industria del Telecomunicaciones", "value": "Industria del Telecomunicaciones"},
  {"label": "Industria Farmacéutica y Biotecnología", "value": "Industria Farmacéutica y Biotecnología"},
  {"label": "Industria Médica", "value": "Industria Médica"},
  {"label": "Industria Metalúrgica y Siderúrgica", "value": "Industria Metalúrgica y Siderúrgica"},
  {"label": "Industria Naval y Marítima", "value": "Industria Naval y Marítima"},
  {"label": "Industria Química y Petroquímica", "value": "Industria Química y Petroquímica"},
  {"label": "Industria Tecnológica", "value": "Industria Tecnológica"},
  {"label": "Industria Textil y Confección", "value": "Industria Textil y Confección"},
  {"label": "Industria Vitivinícola", "value": "Industria Vitivinícola"},
  {"label": "Industria del Papel y Cartón", "value": "Industria del Papel y Cartón"},
  {"label": "Industria del Cine y la Televisión", "value": "Industria del Cine y la Televisión"},
  {"label": "Industria del Deporte", "value": "Industria del Deporte"},
  {"label": "Industria del Entretenimiento", "value": "Industria del Entretenimiento"},
  {"label": "Industria del Petróleo y Gas", "value": "Industria del Petróleo y Gas"},
  {"label": "Industria del Plástico y Caucho", "value": "Industria del Plástico y Caucho"},
  {"label": "Industria del Retail", "value": "Industria del Retail"},
  {"label": "Industria del Software y Desarrollo Web", "value": "Industria del Software y Desarrollo Web"},
  {"label": "Industria del Telecomunicaciones", "value": "Industria del Telecomunicaciones"},
  {"label": "Industria Farmacéutica y Biotecnología", "value": "Industria Farmacéutica y Biotecnología"},
  {"label": "Industria Médica", "value": "Industria Médica"},
  {"label": "Industria Metalúrgica y Siderúrgica", "value": "Industria Metalúrgica y Siderúrgica"},
  {"label": "Industria Naval y Marítima", "value": "Industria Naval y Marítima"},
  {"label": "Industria Química y Petroquímica", "value": "Industria Química y Petroquímica"},
  {"label": "Industria Tecnológica", "value": "Industria Tecnológica"},
  {"label": "Industria Textil y Confección", "value": "Industria Textil y Confección"},
  {"label": "Industria Vitivinícola", "value": "Industria Vitivinícola"},
  {"label": "Industria del Papel y Cartón", "value": "Industria del Papel y Cartón"}
]


export const DataAreaPuesto=[
    {"label": "Tecnologías de la Información (TI)", "value": "Tecnologías de la Información (TI)"},
    {"label": "Negocios y Administración", "value": "Negocios y Administración"},
    {"label": "Salud y Ciencias Médicas", "value": "Salud y Ciencias Médicas"},
    {"label": "Educación", "value": "Educación"},
    {"label": "Ingeniería", "value": "Ingeniería"},
    {"label": "Artes y Entretenimiento", "value": "Artes y Entretenimiento"},
    {"label": "Comunicación y Medios", "value": "Comunicación y Medios"},
    {"label": "Derecho y Ciencias Jurídicas", "value": "Derecho y Ciencias Jurídicas"},
    {"label": "Ciencias Ambientales", "value": "Ciencias Ambientales"},
    {"label": "Arquitectura y Diseño", "value": "Arquitectura y Diseño"},
    {"label": "Ciencia y Tecnología", "value": "Ciencia y Tecnología"},
    {"label": "Ciencias Sociales", "value": "Ciencias Sociales"},
    {"label": "Marketing y Publicidad", "value": "Marketing y Publicidad"},
    {"label": "Turismo y Hospitalidad", "value": "Turismo y Hospitalidad"},
    {"label": "Ventas y Servicio al Cliente", "value": "Ventas y Servicio al Cliente"},
    {"label": "Recursos Naturales y Agricultura", "value": "Recursos Naturales y Agricultura"},
    {"label": "Logística y Transporte", "value": "Logística y Transporte"},
    {"label": "Investigación y Desarrollo", "value": "Investigación y Desarrollo"},
    {"label": "Energía y Recursos Renovables", "value": "Energía y Recursos Renovables"},
    {"label": "Finanzas y Banca", "value": "Finanzas y Banca"},
    {"label": "Exportación y Comercio Internacional", "value": "Exportación y Comercio Internacional"},
    {"label": "Recursos Humanos", "value": "Recursos Humanos"}
  ]